"""Add avatar_filename to User model

Revision ID: 45af3a2bab03
Revises: e63c97211a0b
Create Date: 2025-05-16 13:05:01.459781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45af3a2bab03'
down_revision = 'e63c97211a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_filename')

    # ### end Alembic commands ###
