"""Fix ondelete cascade for comment_id in votes

Revision ID: 61b3e4f54112
Revises: 45af3a2bab03
Create Date: 2025-05-19 00:02:01.381298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b3e4f54112'
down_revision = '45af3a2bab03'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        return  # SQLite doesn't support named constraint dropping

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint('vote_comment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_vote_comment_id',
            'news_comment',
            ['comment_id'],
            ['id'],
            ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'news_comment', ['comment_id'], ['id'])

    # ### end Alembic commands ###
