"""add last_active and current_page to User

Revision ID: d99362d807ab
Revises: 34e515f06fe0
Create Date: 2025-07-23 16:47:58.200674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99362d807ab'
down_revision = '34e515f06fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_message')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('message_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'text'"))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))

    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('needs_scrape',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_page', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_page')
        batch_op.drop_column('last_active')

    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('needs_scrape',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(FALSE)'))

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'text'"))
        batch_op.alter_column('file_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('file_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='fk_message_recipient_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='fk_message_sender_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
